
# 测试http获取faucet,  https://faucet.{env}.sui.io/v1/gas
# env: testnet | devnet | localnet
# reponse
# {
#  "task": "cca52e63-dd56-4f23-9b26-479ee43c83fa",
#  "error": null
# }
POST  https://faucet.testnet.sui.io/v1/gas
Content-Type: application/json

{
  "FixedAmountRequest": {
    "recipient": "your address"
  }
}


###

POST http://localhost:6002/sui/request
Content-Type: application/json

{
  "network": "testnet",
  "address": "your address",
  "amount": "1111"
}


###
POST http://150.158.30.101:6002/sui/request
Content-Type: application/json

{
  "network": "testnet",
  "address": "0xe29fa8db4cb05d9b3b436784f146e1297f65fffdd5f69f7803844a5d81e0850c",
  "amount": "111"
}