
# 测试http获取faucet,  https://faucet.{env}.sui.io/gas
# env: testnet | devnet | localnet
POST  https://faucet.testnet.sui.io/gas
Content-Type: application/json

{
  "FixedAmountRequest": {
    "recipient": "your address"
  }
}


###

POST http://0.0.0.0:6002/sui/request
Content-Type: application/json

{
  "network": "testnet",
  "address": "your address",
  "amount": "1111"
}


###
POST http://150.158.30.101:6002/sui/request
Content-Type: application/json

{
  "network": "testnet",
  "address": "your address",
  "amount": "111"
}